sudo: required
services:
  - docker

before_install:
  - docker build -t root700/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true root700/react-test npm run test -- --coverage

after_success:
  - docker build -t root700/multi-client:latest ./client
  - docker build -t root700/multi-worker:latest ./worker
  - docker build -t root700/multi-nginx:latest ./nginx
  - docker build -t root700/multi-server:latest ./server

  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push root700/multi-client:latest
  - docker push root700/multi-worker:latest
  - docker push root700/multi-nginx:latest
  - docker push root700/multi-server:latest
