sudo: required
services:
  - docker

before_install:
  - docker build -t hristodimitrov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hristodimitrov/react-test npm run test -- --coverage

after_success:
  - docker build -t hristodimitrov/multi-client ./client
  - docker build -t hristodimitrov/multi-worker ./worker
  - docker build -t hristodimitrov/multi-nginx ./nginx
  - docker build -t hristodimitrov/multi-server ./server

